### ISSUE TITLE
not loaded driver

### ISSUE THREAD

**Issue by Cyclohexane1998** [pubglaok00/cheat#12]
Happy chinese new year! 
I have tried the cheat. But I get a "not loaded driver" when I run "guabi.exe". 
If I run "loader64.exe" directly, I will get "unknow error". 
My operating system is windows 11 22H2. 
I have closed "Intel virtual technology" because this cheat cannot run under a virtual machine. 
I have closed Defender.
After the above trial, the error still occur. Can you tell me how to solve this problem?

**Comment by Cyclohexane1998** [comment]
I found this cheat can run in my other computer, whose OS is windows 10.

**Comment by pubglaok00** [comment]
win10 full(not support win11)
