### ISSUE TITLE
reported by other players and banned for one day

### ISSUE THREAD

**Issue by Cyclohexane1998** [pubglaok00/cheat#15]
Using the version 2023/01/22, I successfully cheated yesterday with no more than 5 kills of real players. 
But on Jan 25th, my account was detected and banned for one day when my first game started in this day.
I think the cheat should be updated. Thanks a lot.

BTW, when I am using this cheat, I can cheat during the first two hours. After that, the cheat would turn off if the game time is more than  ten minutes. I check the process. I found the CMD window of guabi.exe and its associated process is also running. But the ESP box and the menu on the lefttop of screen turns off.
I have tried to use another Steam account in the same computer. It can also cheat for two hours. Afterwards, the box also turned off.  I have three accounts. So, I can use them in turn.

**Comment by Cyclohexane1998** [comment]
One of the three accounts has been banned. I guess that it caused by the reports of other players.

**Comment by pubglaok00** [comment]
one day ban==players report ban
permanent ban==detected ban
"ESP box and the menu on the lefttop of screen turns off" "that's ac attack draw randomly" so you need close guabi.exe and run again

**Comment by Cyclohexane1998** [comment]
thanks for the kind answer.
